package knowledge.异常和错误.exception;

import org.junit.Test;

public class BindExceptionDemo {

    @Test
    public void test() {
        /*
         * BindException: Address already in use: bind
         *
         * 端口被占用
         */
    }

}
